CREATE DATABASE HEALTHDB;
USE HEALTHDB;

-- TABLE INFORMATION
SELECT * FROM PATIENTS;
SELECT * FROM APPOINTMENTS;
SELECT * FROM BILLING;
SELECT * FROM DOCTORS;
SELECT * FROM PRESCRIPTIONS;

--  GET ALL APPOINTMENTS FOR A SPECIFIC PATIENT
SELECT * FROM APPOINTMENTS
WHERE PATIENT_ID = 1;

SELECT * FROM PRESCRIPTIONS
WHERE APPOINTMENT_ID = 1;

SELECT * FROM BILLING
WHERE APPOINTMENT_ID = 2;

-- LIST ALL APPOINTMENTS WITH BILLING STATUS
SELECT A.APPOINTMENT_ID,P.FIRST_NAME AS PATIENT_FIRST_NAME,P.LAST_NAME AS PATIENT_LAST_NAME,
D.FIRST_NAME AS DOCTOR_FIRST_NAME,D.LAST_NAME AS DOCTOR_LAST_NAME,
B.AMOUNT,B.PAYMENT_DATE,B.STATUS
FROM APPOINTMENTS A 
JOIN PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
JOIN DOCTORS D ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN  BILLING B ON A.APPOINTMENT_ID = B.APPOINTMENT_ID;

-- FIND ALL Paid billing 
SELECT *  FROM BILLING
WHERE STATUS = 'PAID';

-- CALCULATE TOTAL AMOUNT BILLED AND TOTAL PAID AMOUNT
SELECT
(SELECT SUM(AMOUNT) FROM BILLING) AS TOTAL_BILLED,
(SELECT SUM(AMOUNT) FROM BILLING WHERE STATUS = 'PAID') AS TOTAL_PAID;

-- GET THE NUMBER OF APPOINTMENT BY SPECIALTITY
SELECT D.SPECIALTY,COUNT(A.APPOINTMENT_ID) AS NUMBER_OF_APPOINTMENTS
FROM APPOINTMENTS A
JOIN DOCTORS D ON A.DOCTOR_ID = D.DOCTOR_ID
GROUP BY D.SPECIALTY;

-- FIND THE MOST COMMON REASON FOR APPOINTMENTS 
SELECT REASON,
COUNT(*) AS COUNT
FROM APPOINTMENTS
GROUP BY REASON
ORDER BY COUNT DESC;

-- LIST PATIENTS WITH THEIR LATEST APPOINTMENT DATE
SELECT P.PATIENT_ID,P.FIRST_NAME,P.LAST_NAME,MAX(a.APPOINTMENT_DATE) AS LATEST_APPOINTMENT
FROM PATIENTS P 
JOIN APPOINTMENTS A ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_ID,P.FIRST_NAME,P.LAST_NAME;

-- LIST ALL DOCTORS AND THE NUMBER OF APPOINTMENTS THEY HAD
SELECT D.DOCTOR_ID,D.FIRST_NAME,D.LAST_NAME,COUNT(A.APPOINTMENT_DATE) AS NUMBER_OF_APPOINTMENTS
FROM DOCTORS D 
LEFT JOIN APPOINTMENTS A ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY D.DOCTOR_ID,D.FIRST_NAME,D.LAST_NAME;

-- RETRIEVE PATIENTS WHO HAD APPOINTMENTS IN LAST 90 DAYS
SELECT DISTINCT P.*
FROM PATIENTS P 
JOIN APPOINTMENTS A ON P.PATIENT_ID = A.PATIENT_ID
WHERE STR_TO_DATE(A.APPOINTMENT_DATE, '%d-%m-%Y') >=CURDATE()-INTERVAL  30 DAY;

-- FIND PRESCRIPTIONS ASSOCIATED WITH APPOINTMENTS THAT ARE PENDING PAYMENT
SELECT PR.PRESCRIPTION_ID,PR.MEDICATION,PR.DOSAGE,PR.INSTRUCTIONS
FROM PRESCRIPTIONS PR
JOIN APPOINTMENTS A ON PR.APPOINTMENT_ID = A.APPOINTMENT_ID
JOIN BILLING B ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
WHERE B.STATUS = 'PENDING';

-- ANALYSE PATIENT DEMOGRAPHICS
SELECT GENDER,COUNT(*) AS COUNT
FROM PATIENTS
GROUP BY GENDER;

-- IDENTIFY THE MOST FREQUENTLY PRESCRIBED MEDICATIONS AND THEIR TOTAL DOSAGE
SELECT MEDICATION,COUNT(*) AS FREQUENCY,SUM(CAST(SUBSTRING_INDEX(DOSAGE,' ',1) AS UNSIGNED)) AS TOTAL_DOSAGE
FROM PRESCRIPTIONS
GROUP BY MEDICATION
ORDER BY FREQUENCY DESC;

-- AVERAGE BILLING AMOUNT BY NUMBER OF APPOINTMENTS
SELECT P.PATIENT_ID,COUNT(A.APPOINTMENT_ID) AS APPOITMENT_COUNT,AVG(B.AMOUNT) AS AVG_BILLING_AMOUNT
FROM PATIENTS P 
LEFT JOIN APPOINTMENTS A ON P.PATIENT_ID = A.PATIENT_ID
LEFT JOIN BILLING B ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
GROUP BY P.PATIENT_ID;

-- ANALYZE THE CORREALTION BETWEEN APPOINTMENT FREQUENCY AND BILLING STATUS
SELECT P.PATIENT_ID,P.FIRST_NAME,P.LAST_NAME,SUM(B.AMOUNT) AS TOTAL_BILLED
FROM PATIENTS P 
JOIN APPOINTMENTS A ON P.PATIENT_ID = A.PATIENT_ID
JOIN BILLING B ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
GROUP BY P.PATIENT_ID,P.FIRST_NAME,P.LAST_NAME
ORDER BY TOTAL_BILLED DESC
LIMIT 10;

-- PAYMENT STATUS OVER TIME
SELECT DATE_FORMAT(PAYMENT_DATE, '%Y-%m') AS MONTH,STATUS,COUNT(*) AS COUNT
FROM BILLING
GROUP BY MONTH,STATUS
ORDER BY MONTH,STATUS;

-- DOCTOR PERFORMENCE METRICS
SELECT D.DOCTOR_ID,D.FIRST_NAME,D.LAST_NAME,COUNT(A.APPOINTMENT_DATE) AS NUMBER_OF_APPOINTMENTS
FROM DOCTORS D 
LEFT JOIN APPOINTMENTS A ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY D.DOCTOR_ID,D.FIRST_NAME,D.LAST_NAME;


-- DAY WISE APPOINTMENT COUNTS
SELECT appointment_date,COUNT(*) AS appointment_count
FROM Appointments
GROUP BY appointment_date;


-- FIND PATIENTS WITH MISSING APPOINTMENTS
SELECT p.patient_id,p.first_name,p.last_name
FROM Patients p
LEFT JOIN Appointments a ON p.patient_id=a.patient_id
WHERE a.appointment_id IS NULL;

-- FIND APPOINTMENT WITHOUT BILLING RECORDS
SELECT A.appointment_ID,A.PATIENT_ID,A.DOCTOR_ID,A.APPOINTMENT_DATE
FROM APPOINTMENTS A 
LEFT JOIN BILLING B ON A.appointment_ID = B.appointment_ID
WHERE B.BILLING_ID IS NULL;

-- FIND ALL APPOINTMENTS FOR DOCTOR WITH ID 1 
SELECT A.APPOINTMENT_ID,P.FIRST_NAME AS PATIENT_FIRST_NAME,P.LAST_NAME,A.APPOINTMENT_DATE,A.REASON
FROM APPOINTMENTS A 
JOIN PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
WHERE A.DOCTOR_ID = 1;

-- DATE TABLE CHANGE TO TEXT TO DATE
SET SQL_SAFE_UPDATES=0;

UPDATE APPOINTMENTS 
SET APPOINTMENT_DATE = STR_TO_DATE(APPOINTMENT_DATE,'%d-%m-%Y');

ALTER TABLE APPOINTMENTS
MODIFY COLUMN APPOINTMENT_DATE DATE;

-- LIST ALL PATIENTS WHO HAD APPOINTMENTS IN AUGUST
SELECT DISTINCT P.FIRST_NAME,P.LAST_NAME,P.DOB,P.GENDER,A.APPOINTMENT_DATE
FROM PATIENTS P 
JOIN APPOINTMENTS a ON P.PATIENT_ID = A.PATIENT_ID
WHERE DATE_FORMAT(A.APPOINTMENT_DATE,'%Y-%m') = '2025-08';

-- last all doctors and their appointments in august till today
select d.first_name,d.last_name,a.appointment_date,p.first_name as patients_first_name,p.last_name as patient_last_name
from doctors d 
join appointments a on d.doctor_id=a.doctor_id
join patients p on a.patient_id=p.patient_id 
where a.appointment_date between '2025-08-01' AND '2025-08-10';

-- GET TOTAL AMOUNT BILLED PER DOCTOR
SELECT d.first_name,d.last_name,d.specialty,SUM(b.amount) AS total_billed
FROM Doctors d
JOIN Appointments a ON d.doctor_id=a.doctor_id
JOIN Billing b ON a.appointment_id=b.appointment_id
GROUP BY d.first_name,d.last_name,d.specialty
ORDER BY total_billed desc;